server:
#  port: 8081
  port: 8080

elastic:
  server_url: <server_url>
  server_port: 9243
  api_key: <api_key>
  connection_scheme: https

kafka:
  url: <kafka_url>
  port: 9092

spring:
  kafka:
    bootstrap-servers: <kafka_url>
